log4j.rootLogger=TRACE, STDOUT
log4j.logger.com.vrg.rapid.Cluster=TRACE
log4j.logger.com.vrg.rapid.MembershipService=TRACE
log4j.logger.com.vrg.rapid.Paxos=TRACE
log4j.logger.com.vrg.rapid.FastPaxos=TRACE
log4j.logger.com.vrg.rapid.SharedResources=TRACE
log4j.logger.com.vrg.rapid.messaging.impl.Retries=TRACE
log4j.logger.io.grpc.internal.ManagedChannelOrphanWrapper=TRACE
log4j.appender.STDOUT=org.apache.log4j.ConsoleAppender
log4j.appender.STDOUT.layout=org.apache.log4j.PatternLayout
log4j.appender.STDOUT.layout.ConversionPattern=%5p [%t] (%F:%L) - %m%n